### ISSUE TITLE
Undefined field handling

### ISSUE THREAD

**Issue by vrelk-net** [parseablehq/parseable-datasource#44]
I'm unsure if this is the datasource plugin, or grafana causing this issue.

If you have some records that are missing a field, the key->value associations get shifted.

In my example, I am parsing NGINX web logs, and added the `city` field to the geoip data, so older logs don't contain it.

The query I'm using is `SELECT COUNT(*) as 'count', city, isocode, latitude, longitude FROM nginx WHERE "__log.tag" IN ($log_type) AND "__log.hostname" = '$log_src' AND site_name = '$site_name' GROUP BY city, isocode, latitude, longitude;`

Query inspector data for both: https://gist.github.com/vrelk-net/3b7bc41045a6e8673cf1fcb8b647b300

When the timespan includes mostly data without the `city` field, it disappears from the table columns, but for the records that do have it, it shifts the data over 1 column, and leaves you with a new numbered column at the end.

Last 12 hours:
![image](https://github.com/parseablehq/parseable-datasource/assets/123385045/50f1ada6-c51b-4809-a86c-553be005b7b3)

Last 1 hour:
![image](https://github.com/parseablehq/parseable-datasource/assets/123385045/1599dc71-e41a-42e1-a8af-47f273738a02)

Grafana version: Grafana v11.0.0-169084
Parseable plugin version: 1.2.0

**Comment by nitisht** [comment]
We'll take a look @vrelk-net and get back.

**Comment by dennisvanderweide** [comment]
I have the same problem. It seems that the data pulled from Parseable is incorrectly mapped for use in Grafana. This makes this plugin quite unusable if not every log has the same data fields.

**Comment by erwinschaap** [comment]
I have the same problem

**Comment by nitisht** [comment]
Hey @dennisvanderweide @erwinschaap - thank you for the feedback. We'll get back with a proposal to address this.

**Comment by nitisht** [comment]
We're working on a fix here #45 Should be available in the next release very soon
